#+TITLE: microdata.el

[[https://github.com/Stebalien/microdata.el][microdata.el]] is an Emacs package for extracting and acting on microdata from HTML and emails. Personally, I use this package to open Discourse and GitHub PR/issue notifications from [[https://notmuchmail.org/][notmuch]].

* Configuration
:PROPERTIES:
:ID:       61914056-f94c-4042-baad-89615f558d57
:END:

You'll need to install this package from source with your favorite Emacs package manager. E.g., if you're using at least Emacs 30.1, you can use the ~use-package~ =:vc= keyword as follows.

#+begin_src elisp
(use-package microdata
  :vc (:url "https://github.com/Stebalien/microdata.el"))
#+end_src

Personally, I use this package with notmuch and distribute a notmuch integration library along with it. However, there's no reason it wouldn't work with [[https://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] or [[https://www.gnus.org/][Gnus]].

For example, the following will open the email's default action with =C-c C-c=:

#+begin_src elisp
(use-package notmuch-microdata
  :bind
  (:map notmuch-show-mode-map
  "C-c C-c" 'notmuch-microdata-show-action-view
  :map notmuch-show-mode-map
  "C-c C-c" 'notmuch-microdata-search-action-view))
#+end_src

* API
:PROPERTIES:
:ID:       a1026dd4-206d-4be9-b6fe-3426ce499a9b
:END:

The core [[https://github.com/Stebalien/microdata.el/blob/master/microdata.el][microdata.el]] library provides 4 key functions:

1. ~(microdata-from-html)~ for extracting microdata from a buffer containing HTML.
2. ~(microdata-from-email)~ for extracting microdata from a buffer containing a raw email message.
3. ~(microdata-email-actions)~ for extracting the list of "actions" that can be performed on an email. This list has the form ~(("ActionName" . ((url . "https://some.url") (type . "SomeActionType"))))~.
4. ~(microdata-email-actions-by-type TYPE)~ for extracting the list of "actions" with the given TYPE. This list has the form ~'(("ActionName" . "https://some.url"))~.

With emails, you'll usually want to call ~(microdata-email-actions-by-type "ViewAction")~.
